version: '2'
services:
  web:
    image: "registry.stensuldev.net/dockerfiles/web-2.0.0"
    ports:
    - "127.0.0.1:3000:80"
    volumes:
    - ./storage/logs/:/var/log/
    - .:/usr/src/app
    links:
      - documentstore
      - queue
      - mail
  worker:
    image: "registry.stensuldev.net/dockerfiles/web-2.0.0"
    command: php /usr/src/app/artisan queue:work --daemon
    volumes:
    - ./storage/logs/:/var/log/
    - .:/usr/src/app
    links:
      - documentstore
      - queue
      - mail
  documentstore:
    image: "mongo"
    volumes:
      - ./storage/data/:/data/db
    ports:
      - "127.0.0.1:3001:27017"
  queue:
    image: "redis"
  rockmongo:
    image: "webts/rockmongo"
    ports:
    - "127.0.0.1:8008:80" 
    links:
      - documentstore:db
    environment:
      - DB_NAME=documentstore
      - DB_PORT_27017_TCP_ADDR=documentstore
  mail:
    image: "jeanberu/mailcatcher"
    ports:
      - "127.0.0.1:1080:1080"
    environment:
      - SMTP_PORT=25