web:
  image: "fanbridge/web:v2.0"
  ports:
   - "3000:80"
  volumes:
   - ./storage/logs/:/var/log/
   - .:/usr/src/app
  links:
    - documentstore
    - queue
worker:
  image: "fanbridge/web:v2.0"
  command: php /usr/src/app/artisan queue:work --daemon
  volumes:
   - ./storage/logs/:/var/log/
   - .:/usr/src/app
  links:
    - documentstore
    - queue

documentstore:
  image: "mongo"
  volumes:
    - ./storage/data/:/data/db

queue:
  image: "redis"
