queueweb:
  image: "fanbridge/web:v1.7"
  command: /start.sh
  ports:
   - "49155:80"
  volumes:
   - ../logs/:/var/log/
   - .:/home/stensul/app/


queuebase:
  image: "fanbridge/web:v1.7"
  command: php /home/stensul/app/artisan queue:work --daemon
  volumes:
   - ../logs/:/var/log/
   - .:/home/stensul/app/
